In [1]:
pip install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.6/62.6 kB 1.6 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.2.0-cp311-cp311-win_amd64.whl (96 kB)
     ---------------------------------------- 96.6/96.6 kB 1.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     -------------------------------------- 61.5/61.5 kB 814.3 kB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.0.4-py3-none-any.whl (123 kB)
     ------------------------------------ 123.9/123.9 kB 806.2 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
     -------------------------------------- 158.3/158.3 kB 1.9 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2023.7.22 charset-normalizer-3.2.0 idna-3.4 requests-2.31.0 urllib3-2.0.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [216]:
import requests

In [217]:
access_key = 'fe66583bfe5185048c66571293e0d358'

header = {'access_token': access_key}

In [218]:
baseurl = 'https://globalmart-api.onrender.com'
endpoint = '/mentorskool/v1/sales?offset=1&limit=100'

data=[]
for i in range(5):
    response = requests.get(baseurl+endpoint, headers=header)
    response_data = response.json()
    endpoint = response_data['next']
    data.extend(response.json()['data'])

In [219]:
import pandas as pd
df = pd.json_normalize(data)

In [223]:
df

,id,sales_amt,qty,discount,profit_amt,order.order_id,order.ship_mode,order.order_status,order.order_purchase_date,order.order_approved_at,...,product.product_name,product.colors,product.category,product.sub_category,product.date_added,product.manufacturer,product.sizes,product.upc,product.weight,product.product_photos_qty
0,2698,261.9600,2,0.00,41.9136,CA-2014-145317,Standard Class,delivered,2018-07-11 19:46:00,2018-07-13 15:25,...,Bush Somerset Collection Bookcase,Pink,Furniture,Bookcases,2016-04-01,NaN,9,6.400000e+11,NaN,4
1,6827,731.9400,3,0.00,219.5820,CA-2016-118689,Standard Class,delivered,2018-05-15 20:24:00,2018-05-15 20:55,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Pink,Furniture,Chairs,2016-11-04,NaN,"10,7,6,9,8",6.640000e+11,NaN,2
2,8154,14.6200,2,0.00,6.8714,CA-2017-140151,First Class,delivered,2018-02-28 13:40:00,2018-03-01 13:35,...,Self-Adhesive Address Labels for Typewriters b...,Pink,Office Supplies,Labels,2016-08-01,NaN,11.5,8.870000e+11,NaN,3
3,2624,957.5775,5,0.45,-383.0310,CA-2017-127180,First Class,delivered,2018-01-07 21:45:00,2018-01-07 21:57,...,Bretford CR4500 Series Slim Rectangular Table,Blue,Furniture,Tables,2016-11-15,NaN,"10.5,10,8.5,8,13",8.880000e+11,NaN,0
4,4191,22.3680,2,0.20,2.5164,CA-2017-166709,Standard Class,delivered,2018-02-22 00:06:00,2018-02-22 00:30,...,Eldon Fold 'N Roll Cart System,Blue,Office Supplies,Storage,2016-08-01,NaN,NaN,6.040000e+11,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,336,105.4200,2,0.00,51.6558,CA-2015-137946,Second Class,delivered,2018-03-16 10:34:00,2018-03-17 02:45,...,"Strathmore #10 Envelopes, Ultimate White",Pink,Office Supplies,Envelopes,2015-11-16,NaN,S,8.880000e+11,NaN,4
496,5569,119.6160,8,0.20,40.3704,CA-2017-157966,Same Day,delivered,2018-03-08 15:59:00,2018-03-08 16:30,...,Clear Mylar Reinforcing Strips,Pink,Office Supplies,Binders,2016-02-21,NaN,NaN,7.130000e+11,NaN,3
497,8821,255.7600,4,0.00,81.8432,CA-2017-100622,Standard Class,delivered,2018-03-01 21:16:00,2018-03-01 21:30,...,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",Pink,Furniture,Furnishings,2017-01-27,Franco Sarto,"8.5,9.5,7.5,9,8,11",7.200000e+11,NaN,0
498,2898,241.5680,2,0.20,18.1176,US-2016-164630,Standard Class,delivered,2018-03-15 18:39:00,2018-03-15 18:50,...,DMI Arturo Collection Mission-style Design Woo...,Pink,Furniture,Chairs,2016-03-15,NaN,NaN,8.820000e+11,NaN,4
499,4,69.3000,9,0.00,22.8690,US-2015-108966,Standard Class,delivered,2018-04-14 00:04:00,2018-04-14 00:29,...,Deflect-O Glasstique Clear Desk Accessories,Pink,Furniture,Furnishings,2016-05-21,NaN,NaN,NaN,NaN,0

In [220]:
df[:5]

,id,sales_amt,qty,discount,profit_amt,order.order_id,order.ship_mode,order.order_status,order.order_purchase_date,order.order_approved_at,...,product.product_name,product.colors,product.category,product.sub_category,product.date_added,product.manufacturer,product.sizes,product.upc,product.weight,product.product_photos_qty
0,2698,261.9600,2,0.00,41.9136,CA-2014-145317,Standard Class,delivered,2018-07-11 19:46:00,2018-07-13 15:25,...,Bush Somerset Collection Bookcase,Pink,Furniture,Bookcases,2016-04-01,null,9,640000000000,null,4
1,6827,731.9400,3,0.00,219.5820,CA-2016-118689,Standard Class,delivered,2018-05-15 20:24:00,2018-05-15 20:55,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Pink,Furniture,Chairs,2016-11-04,null,"10,7,6,9,8",664000000000,null,2
2,8154,14.6200,2,0.00,6.8714,CA-2017-140151,First Class,delivered,2018-02-28 13:40:00,2018-03-01 13:35,...,Self-Adhesive Address Labels for Typewriters b...,Pink,Office Supplies,Labels,2016-08-01,null,11.5,887000000000,null,3
3,2624,957.5775,5,0.45,-383.0310,CA-2017-127180,First Class,delivered,2018-01-07 21:45:00,2018-01-07 21:57,...,Bretford CR4500 Series Slim Rectangular Table,Blue,Furniture,Tables,2016-11-15,null,"10.5,10,8.5,8,13",888000000000,null,0
4,4191,22.3680,2,0.20,2.5164,CA-2017-166709,Standard Class,delivered,2018-02-22 00:06:00,2018-02-22 00:30,...,Eldon Fold 'N Roll Cart System,Blue,Office Supplies,Storage,2016-08-01,null,null,604000000000,null,0

In [221]:
import numpy as np
df = df.replace('null', np.nan)

null_counts = df.isnull().sum()

print(null_counts)

id                                       0
sales_amt                                0
qty                                      0
discount                                 0
profit_amt                               0
order.order_id                           0
order.ship_mode                          0
order.order_status                       0
order.order_purchase_date                0
order.order_approved_at                  2
order.order_delivered_carrier_date       7
order.order_delivered_customer_date     12
order.order_estimated_delivery_date      2
order.customer.customer_id               0
order.customer.customer_name             0
order.customer.segment                   0
order.customer.contact_number            0
order.customer.address.zip_code          0
order.customer.address.region            0
order.customer.address.country           0
order.customer.address.city              0
order.customer.address.state             0
order.vendor.VendorID                    0
order.vendor.Vendor Name                 0
product.product_id                       0
product.product_name                     0
product.colors                           0
product.category                         0
product.sub_category                     0
product.date_added                       0
product.manufacturer                   297
product.sizes                          340
product.upc                            201
product.weight                         467
product.product_photos_qty               0
dtype: int64

In [224]:
duplicate_records = df[df.duplicated(keep=False)]

# Print the duplicate records
print("Duplicate records:")
print(duplicate_records)

Duplicate records:
Empty DataFrame
Columns: [id, sales_amt, qty, discount, profit_amt, order.order_id, order.ship_mode, order.order_status, order.order_purchase_date, order.order_approved_at, order.order_delivered_carrier_date, order.order_delivered_customer_date, order.order_estimated_delivery_date, order.customer.customer_id, order.customer.customer_name, order.customer.segment, order.customer.contact_number, order.customer.address.zip_code, order.customer.address.region, order.customer.address.country, order.customer.address.city, order.customer.address.state, order.vendor.VendorID, order.vendor.Vendor Name, product.product_id, product.product_name, product.colors, product.category, product.sub_category, product.date_added, product.manufacturer, product.sizes, product.upc, product.weight, product.product_photos_qty]
Index: []

[0 rows x 35 columns]

In [226]:
df['order.order_purchase_date'] = pd.to_datetime(df['order.order_purchase_date'])

# Get the day of the week for each order (0 represents Monday, 6 represents Sunday)
df['day_of_week'] = df['order.order_purchase_date'].dt.dayofweek

# Count the number of orders placed on weekends (Saturday and Sunday)
weekend_orders = df[df['day_of_week'].isin([5, 6])]

# Get the count of weekend orders
num_weekend_orders = len(weekend_orders)

print("Number of orders placed on weekends:", num_weekend_orders)

Number of orders placed on weekends: 99

In [228]:
df['order.order_purchase_date'] = pd.to_datetime(df['order.order_purchase_date'])

# Get the day of the week for each order (0 represents Monday, 6 represents Sunday)
df['day_of_week'] = df['order.order_purchase_date'].dt.dayofweek

# Group the data by the day of the week and calculate the total sales for each group
sales_by_day = df.groupby('day_of_week')['sales_amt'].sum()

# Get the total sales for weekends (Saturday and Sunday)
weekend_sales = sales_by_day.loc[[5, 6]].sum()

# Get the total sales for weekdays (Monday to Friday)
weekday_sales = sales_by_day.loc[[0, 1, 2, 3, 4]].sum()

# Compare the total sales for weekends and weekdays to determine the highest sales
print("weekend_sales: ", weekend_sales)
print("weekday_sales: ", weekday_sales)
if weekend_sales > weekday_sales:
    print("Weekend has the highest sales.")
elif weekend_sales < weekday_sales:
    print("Weekdays have the highest sales.")
else:
    print("Weekends and weekdays have the same sales.")

weekend_sales:  20900.1495
weekday_sales:  108526.1666
Weekdays have the highest sales.